import json, os

json_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'glossary.json')
with open(json_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

TR_NAMES = {
    "Acceptance Criteria": "Kabul Kriterleri",
    "Actual Cost (AC)": "Gerçekleşen Maliyet (AC)",
    "Adaptive Approach": "Uyarlanabilir Yaklaşım",
    "Agile": "Çevik",
    "Agile Manifesto": "Çevik Manifesto",
    "Appraisal Cost": "Değerlendirme Maliyeti",
    "Assumption": "Varsayım",
    "Assumption Log": "Varsayım Kaydı",
    "Backlog Refinement": "İş Birikim Listesi İyileştirme",
    "Baseline": "Temel Çizgi",
    "Benchmarking": "Kıyaslama",
    "Benefit-Cost Ratio (BCR)": "Fayda-Maliyet Oranı (BCR)",
    "Benefits Realization": "Fayda Gerçekleştirme",
    "Budget at Completion (BAC)": "Tamamlanma Bütçesi (BAC)",
    "Burndown Chart": "Kalan İş Grafiği",
    "Burnup Chart": "Tamamlanan İş Grafiği",
    "Business Case": "İş Gerekçesi",
    "Business Value": "İş Değeri",
    "Cause-and-Effect Diagram": "Neden-Sonuç Diyagramı (Ishikawa)",
    "Change Control Board (CCB)": "Değişiklik Kontrol Kurulu (DKK)",
    "Change Request": "Değişiklik Talebi",
    "Communication Channels Formula": "İletişim Kanalları Formülü",
    "Communication Methods": "İletişim Yöntemleri",
    "Communications Management Plan": "İletişim Yönetim Planı",
    "Configuration Management": "Konfigürasyon Yönetimi",
    "Conflict Resolution Techniques": "Çatışma Çözme Teknikleri",
    "Constraint": "Kısıt",
    "Contingency Reserve": "Acil Durum Yedeği",
    "Continuous Improvement": "Sürekli İyileştirme",
    "Control Charts": "Kontrol Grafikleri",
    "Cost Baseline": "Maliyet Temel Çizgisi",
    "Cost Management Plan": "Maliyet Yönetim Planı",
    "Cost Performance Index (CPI)": "Maliyet Performans Endeksi (CPI)",
    "Cost Reimbursable Contract": "Masraf Geri Ödemeli Sözleşme",
    "Cost Variance (CV)": "Maliyet Sapması (CV)",
    "Cost of Quality (COQ)": "Kalite Maliyeti (COQ)",
    "Crashing": "Sıkıştırma",
    "Critical Path": "Kritik Yol",
    "Critical Path Method (CPM)": "Kritik Yol Yöntemi (CPM)",
    "Daily Scrum": "Günlük Scrum (Stand-up)",
    "Decision Tree Analysis": "Karar Ağacı Analizi",
    "Decomposition": "Ayrıştırma",
    "Definition of Done (DoD)": "Tamamlanmışın Tanımı (DoD)",
    "Definition of Ready (DoR)": "Hazırın Tanımı (DoR)",
    "Deliverable": "Teslimat",
    "Delivery Performance Domain": "Teslimat Performans Alanı",
    "Development Approach": "Geliştirme Yaklaşımı",
    "Development Approach and Life Cycle Performance Domain": "Geliştirme Yaklaşımı ve Yaşam Döngüsü Performans Alanı",
    "Earned Value (EV)": "Kazanılmış Değer (EV)",
    "Earned Value Management (EVM)": "Kazanılmış Değer Yönetimi (KDY)",
    "Emotional Intelligence (EI)": "Duygusal Zeka",
    "Enterprise Environmental Factors (EEF)": "Çevresel İşletme Faktörleri (ÇİF)",
    "Epic": "Epic (Büyük Kullanıcı Hikayesi)",
    "Estimate at Completion (EAC)": "Tamamlama Tahmini (EAC)",
    "Estimate to Complete (ETC)": "Tamamlamak İçin Tahmin (ETC)",
    "Expected Monetary Value (EMV)": "Beklenen Parasal Değer (BPD)",
    "External Failure Cost": "Dış Hata Maliyeti",
    "Fast Tracking": "Hızlı İzleme",
    "Feature": "Özellik",
    "Finish-to-Finish (FF)": "Bitiş-Bitiş (BB)",
    "Finish-to-Start (FS)": "Bitiş-Başlangıç (BB)",
    "Fixed-Price Contract": "Sabit Fiyatlı Sözleşme",
    "Float (Slack)": "Bolluk / Serbesti",
    "Free Float": "Serbest Bolluk",
    "Gold Plating": "Altın Kaplama",
    "Governance": "Yönetişim",
    "Herzberg's Two-Factor Theory": "Herzberg'in İki Faktör Teorisi",
    "Hybrid Approach": "Hibrit Yaklaşım",
    "Incremental Approach": "Artımlı Yaklaşım",
    "Information Radiator": "Bilgi Yayıcı / Görsel Bilgi Ekranı",
    "Integrated Change Control": "Entegre Değişiklik Kontrolü",
    "Internal Failure Cost": "İç Hata Maliyeti",
    "Internal Rate of Return (IRR)": "İç Getiri Oranı (IRR)",
    "Issue": "Sorun",
    "Issue Log": "Sorun Kaydı",
    "Iterative Approach": "Yinelemeli Yaklaşım",
    "Kaizen": "Kaizen (Sürekli Küçük İyileştirme)",
    "Kanban": "Kanban",
    "Lag": "Gecikme / Öteleme",
    "Lead": "Öne Çekme",
    "Lean": "Yalın Yönetim",
    "Lessons Learned": "Öğrenilmiş Dersler",
    "Lessons Learned Register": "Öğrenilmiş Dersler Kaydı",
    "Life Cycle Cost": "Yaşam Döngüsü Maliyeti",
    "Management Reserve": "Yönetim Yedeği",
    "Maslow's Hierarchy of Needs": "Maslow'un İhtiyaçlar Hiyerarşisi",
    "McClelland's Theory of Needs": "McClelland'ın İhtiyaçlar Teorisi",
    "McGregor's Theory X and Theory Y": "McGregor'un X ve Y Teorisi",
    "Measurement Performance Domain": "Ölçüm Performans Alanı",
    "Milestone": "Kilometre Taşı",
    "Minimum Viable Product (MVP)": "Minimum Yapılabilir Ürün (MVP)",
    "Monte Carlo Simulation": "Monte Carlo Simülasyonu",
    "Net Present Value (NPV)": "Net Bugünkü Değer (NBD)",
    "Network Diagram": "Ağ Diyagramı",
    "Opportunity Cost": "Fırsat Maliyeti",
    "Organizational Breakdown Structure (OBS)": "Organizasyonel Kırılım Yapısı (OKY)",
    "Organizational Process Assets (OPA)": "Organizasyonel Süreç Varlıkları (OSV)",
    "Outcome": "Sonuç / Çıktı",
    "PMBOK® Guide Principle: Adaptability & Resilience": "Uyarlanabilirlik ve Dayanıklılık",
    "PMBOK® Guide Principle: Change": "Değişimi Benimse",
    "PMBOK® Guide Principle: Complexity": "Karmaşıklıkla Başa Çık",
    "PMBOK® Guide Principle: Leadership": "Liderliği Sergile",
    "PMBOK® Guide Principle: Quality": "Kaliteyi Süreçlere İşle",
    "PMBOK® Guide Principle: Risk": "Risk Yanıtlarını Optimize Et",
    "PMBOK® Guide Principle: Stakeholders": "Paydaşları Dahil Et",
    "PMBOK® Guide Principle: Stewardship": "Titiz Bir Yönetici Ol",
    "PMBOK® Guide Principle: Systems Thinking": "Sistemik Düşün",
    "PMBOK® Guide Principle: Tailoring": "Yaklaşımını Uyarla",
    "PMBOK® Guide Principle: Team": "İşbirlikçi Takım Ortamı Oluştur",
    "PMBOK® Guide Principle: Value": "Değere Odaklan",
    "PMO (Project Management Office)": "Proje Yönetim Ofisi (PYO)",
    "Pareto Chart": "Pareto Grafiği",
    "Payback Period": "Geri Ödeme Süresi",
    "Performance Measurement Baseline (PMB)": "Performans Ölçüm Temel Çizgisi (PMB)",
    "Phase Gate": "Faz Kapısı",
    "Planned Value (PV)": "Planlanan Değer (PV)",
    "Planning Performance Domain": "Planlama Performans Alanı",
    "Planning Poker": "Planlama Pokeri",
    "Portfolio": "Portföy",
    "Power/Interest Grid": "Güç/İlgi Matrisi",
    "Precedence Diagramming Method (PDM)": "Öncelik Diyagram Yöntemi (ÖDY)",
    "Predictive Approach": "Öngörücü Yaklaşım (Şelale)",
    "Prevention Cost": "Önleme Maliyeti",
    "Probability and Impact Matrix": "Olasılık ve Etki Matrisi",
    "Product Backlog": "Ürün Birikim Listesi",
    "Product Owner": "Ürün Sahibi",
    "Program": "Program",
    "Progressive Elaboration": "Aşamalı Detaylandırma",
    "Project": "Proje",
    "Project Charter": "Proje Başlatma Belgesi",
    "Project Closure": "Proje Kapanışı",
    "Project Life Cycle": "Proje Yaşam Döngüsü",
    "Project Management": "Proje Yönetimi",
    "Project Management Plan": "Proje Yönetim Planı",
    "Project Manager": "Proje Yöneticisi",
    "Project Roadmap": "Proje Yol Haritası",
    "Project Work Performance Domain": "Proje Çalışması Performans Alanı",
    "RACI Matrix": "RACI Matrisi",
    "Request for Proposal (RFP)": "Teklif Talebi (RFP)",
    "Requirements": "Gereksinimler",
    "Resource Leveling": "Kaynak Dengeleme",
    "Resource Smoothing": "Kaynak Düzleştirme",
    "Responsibility Assignment Matrix (RAM)": "Sorumluluk Atama Matrisi",
    "Retrospective": "Retrospektif / Geçmişe Bakış",
    "Risk": "Risk",
    "Risk Appetite": "Risk İştahı",
    "Risk Register": "Risk Kaydı",
    "Risk Response Strategies": "Risk Yanıt Stratejileri",
    "Rolling Wave Planning": "Kayan Dalga Planlama",
    "Salience Model": "Belirginlik Modeli",
    "Schedule Baseline": "Zaman Çizelgesi Temel Çizgisi",
    "Schedule Performance Index (SPI)": "Zaman Çizelgesi Performans Endeksi (SPI)",
    "Schedule Variance (SV)": "Zaman Çizelgesi Sapması (SV)",
    "Scope Baseline": "Kapsam Temel Çizgisi",
    "Scope Creep": "Kapsam Kayması",
    "Scrum": "Scrum",
    "Scrum Master": "Scrum Master",
    "Servant Leadership": "Hizmetkar Liderlik",
    "Six Sigma": "Altı Sigma",
    "Sponsor": "Proje Sponsoru",
    "Sprint": "Sprint / Yineleme",
    "Sprint Backlog": "Sprint Birikim Listesi",
    "Sprint Planning": "Sprint Planlaması",
    "Sprint Retrospective": "Sprint Retrospektifi",
    "Sprint Review": "Sprint İncelemesi",
    "Stakeholder": "Paydaş",
    "Stakeholder Engagement Plan": "Paydaş Katılım Planı",
    "Stakeholder Performance Domain": "Paydaş Performans Alanı",
    "Stakeholder Register": "Paydaş Kaydı",
    "Start-to-Finish (SF)": "Başlangıç-Bitiş (BF)",
    "Start-to-Start (SS)": "Başlangıç-Başlangıç (BB)",
    "Statement of Work (SOW)": "İş Bildirimi (SOW)",
    "Story Points": "Hikaye Puanları",
    "Sunk Cost": "Batık Maliyet",
    "Tailoring": "Uyarlama",
    "Team Performance Domain": "Takım Performans Alanı",
    "Technical Debt": "Teknik Borç",
    "Three-Point Estimate (PERT)": "Üç Noktalı Tahmin (PERT)",
    "Time and Material Contract": "Zaman ve Malzeme Sözleşmesi",
    "Timeboxing": "Zaman Kutusu / Zaman Sınırlaması",
    "To-Complete Performance Index (TCPI)": "Tamamlamak İçin Performans Endeksi (TCPI)",
    "Total Float": "Toplam Bolluk",
    "Tuckman's Stages of Team Development": "Tuckman Takım Gelişim Modeli",
    "Uncertainty Performance Domain": "Belirsizlik Performans Alanı",
    "User Story": "Kullanıcı Hikayesi",
    "Value": "Değer",
    "Variance at Completion (VAC)": "Tamamlanma Sapması (VAC)",
    "Velocity": "Hız (Velocity)",
    "WBS Dictionary": "İKY Sözlüğü",
    "WIP Limit": "Devam Eden İş Limiti (WIP Limiti)",
    "Work Breakdown Structure (WBS)": "İş Kırılım Yapısı (İKY)",
}

TR_DEFS = {
    "Acceptance Criteria": "Bir ürünün, hizmetin veya sonucun müşteri veya sponsor tarafından resmi olarak kabul edilebilmesi için karşılaması gereken standartlar ve koşullar dizisidir.",
    "Actual Cost (AC)": "Belirli bir zaman diliminde bir faaliyet üzerinde gerçekleştirilen iş için katlanılan gerçekleşmiş, net maliyettir.",
    "Assumption": "Planlama ve risk süreçlerinde, aksine bir kanıt veya gösterge olmaksızın doğru, gerçek veya kesin olarak kabul edilen faktörlerdir.",
    "Backlog Refinement": "Aşırı karmaşık veya büyük hikayelerin (epic) daha alt parçalara bölünerek detaylandırılmasını sağlayan ve takımın bunları daha hızlı tamamlamasına olanak tanıyan toplantı/çalışmadır.",
    "Benchmarking": "En iyi uygulamaları belirlemek ve iyileştirme için fikirler üretmek amacıyla gerçek veya planlanmış proje süreçlerini diğer benzer organizasyonlarınkilerle karşılaştırma işlemidir.",
    "Budget at Completion (BAC)": "Gerçekleştirilecek proje işi için kurulan/onaylanan orijinal tahmini bütçelerin tümünün toplamıdır.",
    "Burndown Chart": "Tamamlanması gereken veya kalan iş miktarını belirli bir zaman dilimine karşı gösteren ve genellikle çevik projelerde takımın hızını izlemek için kullanılan bir araçtır.",
    "Burnup Chart": "Zamana karşı tamamlanan iş miktarını gösteren, aynı zamanda projenin toplam kapsamındaki değişikliklerin de takip edilmesini sağlayan görsel bir bilgi grafiğidir.",
    "Cause-and-Effect Diagram": "Bir sorunun nedenlerini ayrı dallara (kılçık modeline) bölerek ana veya kök nedeni belirlemeye ve aykırı değerleri ortaya çıkarmaya yardımcı olan analiz aracıdır.",
    "Change Control Board (CCB)": "Projedeki değişiklik taleplerini gözden geçirmek, değerlendirmek, onaylamak, ertelemek veya reddetmek ve bu kararları iletmekle yetkilendirilmiş resmi gruptur.",
    "Change Request": "Projenin kapsam, zaman çizelgesi, maliyet veya kalite temel çizgilerinde ya da belgelerinde resmi bir değişiklik yapılması için sunulan öneridir.",
    "Conflict Resolution Techniques": "Anlaşmazlıkları çözmek için kullanılan temel PMI yaklaşımları: İşbirliği/Problem Çözme (en iyi), Uzlaşma, Pürüzsüzleştirme, Zorlama ve Kaçınma.",
    "Contingency Reserve": "Bilinen riskleri (önceden tanımlanmış ve öngörülen sorunları) ele almak için proje bütçesine veya zaman çizelgesine eklenen ve doğrudan proje yöneticisinin kontrolü altında olan fon veya zaman yedekleridir.",
    "Control Charts": "Bir sürecin zaman içinde stabil olup olmadığını veya kontrol limitleri içinde kalarak öngörülebilir bir performansa sahip olup olmadığını belirlemek için kullanılan kalite aracıdır.",
    "Cost Performance Index (CPI)": "Kazanılmış değerin (EV), gerçekleşen maliyete (AC) bölünmesiyle elde edilen ve bir projenin maliyet verimliliğini ölçen formüldür.",
    "Cost Variance (CV)": "Kazanılmış Değer'den (EV) Gerçekleşen Maliyetin (AC) çıkarılmasıyla hesaplanır. Negatif bir maliyet sapması, projenin bütçeyi aştığı anlamına gelir.",
    "Cost of Quality (COQ)": "Hataların azaltılmasına yönelik önleyici maliyetler, değerlendirme maliyetleri (denetimler) ve hem iç hem de dış hatalarla ilgili başarısızlık maliyetlerinin toplamını ifade eder.",
    "Crashing": "Zaman çizelgesini kısaltmak için bütçeyi artırarak kritik yol üzerindeki faaliyetlere daha fazla personel veya kaynak ekleme yöntemidir.",
    "Critical Path Method (CPM)": "Bir projenin zaman çizelgesi modelini oluşturmak ve ağ diyagramı üzerinden projenin tamamlanması için gereken en uzun ve en az esnekliğe sahip süreyi belirlemek için kullanılan hesaplama yöntemidir.",
    "Daily Scrum": "Çevik takımların her gün ilerlemeyi gözden geçirmek, o günkü işleri planlamak ve engelleri tespit etmek için yaptıkları kısa, genellikle 15 dakikalık zaman kutulu senkronizasyon toplantısıdır.",
    "Decision Tree Analysis": "Birden fazla seçeneğin olduğu durumlarda, her bir seçeneğin potansiyel maliyetlerini, risklerini ve beklenen faydalarını matematiksel olarak değerlendirmek için kullanılan karar modelleme tekniğidir.",
    "Definition of Done (DoD)": "Bir müşteri veya paydaş tarafından tamamlanmış bir görev veya hikayenin kabul edilebilmesi için mutlaka karşılanması gereken kalite kriterlerinin listesidir.",
    "Definition of Ready (DoR)": "Çevik projelerde, bir kullanıcı hikayesinin tahminleme yapılmadan önce geliştirilmeye 'hazır' olduğunu onaylamak için karşılanması gereken spesifik kabul kriterleridir.",
    "Earned Value (EV)": "Projede o ana kadar fiziksel olarak tamamlanan işin değerini, o işe atanmış olan orijinal onaylı bütçe üzerinden matematiksel olarak ifade eden performans ölçümüdür.",
    "Enterprise Environmental Factors (EEF)": "Proje takımının doğrudan kontrolü altında olmayan, ancak projenin yönetimini etkileyen, kısıtlayan veya yönlendiren iç ve dış koşullardır.",
    "Estimate at Completion (EAC)": "Proje devam ederken geçmiş proje performansına ve gerçekleşen maliyetlere (AC) dayanarak, projenin tamamen bittiğinde ulaşacağı toplam maliyetin revize edilmiş ve güncel projeksiyonudur.",
    "Fast Tracking": "Proje süresini kısaltmak amacıyla normal şartlarda ardışık yapılacak faaliyetlerin veya proje fazlarının eşzamanlı veya paralel olarak yürütülmesidir.",
    "Hybrid Approach": "İki veya daha fazla çevik (agile) ve çevik olmayan (şelale) unsurun birleştirildiği, genellikle çıktının çevik olmadığı melez proje yönetimi modelidir.",
    "Information Radiator": "Takımın ilerlemesini, durumunu, çalışma hızını ve darboğazlarını organizasyon genelinde şeffafça paylaşmak için çalışma alanında herkesin görebileceği şekilde tutulan fiziksel veya dijital bilgi ekranlarıdır.",
    "Lag": "Fiziksel kısıtlamalar veya kaynak kısıtları durumunda, başka bir faaliyetin bitmesini beklemek için sonraki faaliyetlerin başlangıcına eklenen zorunlu bekleme süreleridir.",
    "Lead": "Proje zaman çizelgesini kısaltmak için, önceki bir faaliyet henüz tamamen bitmeden bir sonraki bağımlı faaliyetin erken başlatılmasıdır.",
    "Lessons Learned Register": "Geçmişteki veya mevcut projelerden elde edilen; takımın neleri iyi yaptığını, nerelerde hata yaptığını barındıran ve gelecekteki projeleri iyileştirmek için hazırlanan resmi belgedir.",
    "Management Reserve": "Kapsam içinde yer alan ancak tamamen öngörülemeyen 'bilinmeyen-bilinmeyen' riskler için maliyet veya zaman çizelgesi temel çizgisine eklenen, kullanımı için üst yönetimin onayı gereken zaman veya bütçe tamponudur.",
    "Milestone": "Bir projede, programda veya portföyde önemli bir anı, tamamlanmış bir olayı veya kritik bir aşamayı temsil eden (genellikle süresi sıfır olan) zaman noktasıdır.",
    "Minimum Viable Product (MVP)": "Müşterilere değer sunmak, pazarın rekabetine ilk giren olmak ve kullanıcı geri bildirimi toplamak amacıyla piyasaya sürülen, sistemin en temel özelliklerini içeren küçük artımlı ilk versiyondur.",
    "Network Diagram": "Proje faaliyetlerini bağımlılıklarına dayalı olarak sıralamak ve görselleştirmek için kullanılan grafiksel gösterimdir.",
    "Organizational Process Assets (OPA)": "Organizasyon tarafından geçmiş projelerde oluşturulan ve yeni projelerde kullanılan rehberler, şablonlar, prosedürler, politikalar ve öğrenilmiş dersler havuzu gibi bilgi birikimi depolarıdır.",
    "Pareto Chart": "Projedeki sorunların veya hataların kök nedenlerini analiz etmek ve enerjiyi hataların %80'ine neden olan %20'lik sebebe odaklamak amacıyla kullanılan, sorunları en çoktan en aza doğru sıralayan çubuk grafiğidir.",
    "Planned Value (PV)": "Belirli bir dönemde bitirilmesi planlanmış ve zamanlanmış iş için başlangıçta yetkilendirilmiş ve ayrılmış olan bütçe miktarıdır.",
    "Portfolio": "Bir organizasyonun stratejik iş hedeflerine ulaşmak amacıyla bir grup olarak yönetilen projeler, programlar ve operasyonların tamamıdır.",
    "Predictive Approach": "Bir projenin kapsamının, zamanının ve maliyetinin projenin başlarında kapsamlı bir planlamayla belirlendiği geleneksel, ardışık geliştirme yaklaşımıdır. Şelale modeli olarak da bilinir.",
    "Program": "Ortak bir amaca hizmet eden, ancak bireysel olarak yönetildiklerinde elde edilemeyecek düzeyde faydalar sağlamak amacıyla koordineli bir biçimde yönetilen birbiriyle ilişkili projeler bütünüdür.",
    "Progressive Elaboration": "Daha fazla bilgi ve daha doğru tahminler elde edildikçe, bir proje yönetim planındaki ayrıntı düzeyini sürekli ve yinelemeli olarak artırma sürecidir.",
    "Project": "Yeni, özgün bir ürün, hizmet veya sonuç yaratmak amacıyla üstlenilen; tanımlanmış bir başlangıcı ve bitişi olan geçici bir girişimdir.",
    "Project Charter": "Bir projeyi resmi olarak var eden, projenin temel hedeflerini, iş gerekçesini ve kısıtlarını içeren ve proje yöneticisine organizasyonel kaynakları kullanma yetkisi atayan, sponsor tarafından imzalanan temel belgedir.",
    "Project Life Cycle": "Bir projenin başlatılmasından, planlanmasına, yürütülmesine ve kapanışına kadar geçtiği birbirini takip eden evreler veya aşamalar dizisidir.",
    "Project Management Plan": "Projenin hedeflerine nasıl ulaşacağını; işin nasıl yürütüleceğini, izleneceğini, kontrol edileceğini ve kapatılacağını tanımlayan temel çizgileri ve tüm alt yönetim planlarını barındıran entegre ana dokümandır.",
    "PMO (Project Management Office)": "Projelerle ilgili yönetişim süreçlerini standartlaştıran ve metodolojilerin, araçların, eğitimlerin ve kaynakların projeler arasında paylaşımını kolaylaştıran merkezi departmandır.",
    "RACI Matrix": "Bir projede her bir görevin kimin sorumluluğunda olduğunu netleştirmek için kullanılan; Sorumlu (R), Hesap Veren (A), Danışılan (C) ve Bilgilendirilen (I) rollerini tanımlayan sorumluluk atama matrisidir.",
    "Retrospective": "Çevik bir iterasyonun veya projenin sonunda, takımın geçmiş performansı masaya yatırdığı; nelerin iyi gittiğini, nelerin yanlış gittiğini ve ne iyileştirileceğini şeffafça tartışıp sürekli iyileştirme sağladığı toplantıdır.",
    "Risk": "Gerçekleşmesi durumunda projenin hedeflerinden en az biri üzerinde olumlu (fırsat) veya olumsuz (tehdit) etki yaratan belirsiz bir olaydır.",
    "Risk Register": "Proje süresince tanımlanan risklerin detaylarının (olasılık, etki) ve bu riskler için geliştirilen yanıt stratejilerinin listelendiği ve izlendiği temel belgedir.",
    "Risk Response Strategies": "Fırsatlar için: Sömürme, Geliştirme, Paylaşma. Tehditler için: Kaçınma, Azaltma/Hafifletme, Transfer Etme. Hem fırsatlar hem tehditler için: Kabul etme.",
    "Salience Model": "Paydaşları güç (power), aciliyet (urgency) ve meşruiyet (legitimacy) özelliklerine göre sınıflandıran, liderlerin karmaşık paydaş ilişkilerinde doğru kişilere odaklanmasına yardımcı olan analiz modelidir.",
    "Schedule Performance Index (SPI)": "Kazanılmış değerin (EV), planlanan değere (PV) bölünmesiyle hesaplanan ve proje ekibinin zaman planına ne kadar verimli uyduğunu gösteren matematiksel ölçüdür.",
    "Schedule Variance (SV)": "Kazanılmış Değer'den (EV) Planlanan Değerin (PV) çıkarılmasıyla hesaplanır. Negatif bir zaman çizelgesi sapması, projenin orijinal takvimin gerisinde kaldığı anlamına gelir.",
    "Scope Baseline": "Resmi kapsam belgelerinin (İKY ve İKY Sözlüğü dahil) onaylanmış versiyonudur; yalnızca değişiklik kontrol prosedürleri kullanılarak değiştirilebilir.",
    "Scope Creep": "Proje veya ürün kapsamının; zaman, maliyet ve kaynaklar için herhangi bir resmi ayarlama veya değişiklik kontrolü yapılmadan kontrolsüz bir şekilde genişlemesi durumudur.",
    "Servant Leadership": "Liderin sonuçları tek başına dikte etmek yerine, takım üyelerinin ihtiyaçlarını anlamaya, takımı engellere karşı korumaya ve onların en yüksek performansa ulaşması için ortak karar almaya odaklandığı liderlik pratiğidir.",
    "Sponsor": "Bir proje veya portföy için finansmanı ve temel kaynakları sağlayan, projenin iş değeri üretmesinden sorumlu olan ve genellikle teslimatları nihai olarak imzalayan kişi veya gruptur.",
    "Sprint": "Scrum ve Çevik çerçevelerde, çalışan ve test edilebilir bir ürün artırımının geliştirildiği, genellikle 1 ila 4 hafta arasında süren sabit uzunluktaki zaman kutusudur.",
    "Stakeholder": "Bir projenin, programın veya portföyün yürütülmesinden veya nihai sonucundan etkilenebilecek, projeyi etkileyebilecek veya etkilendiğini düşünebilecek her türlü kişi, grup veya kuruluştur.",
    "Statement of Work (SOW)": "Proje tarafından teslim edilecek nihai ürün, hizmet veya sonuçların anlatısal (metin tabanlı) bir açıklamasıdır.",
    "Timeboxing": "Belirli bir hedefe ulaşmak, bir görevi tamamlamak veya bir toplantıyı yapmak için ayrılmış, süresi asla uzatılamayacak, sınırları kesin olarak belirlenmiş maksimum zaman aralığıdır.",
    "Tuckman's Stages of Team Development": "Takım dinamiklerini açıklayan dört aşamalı model: Oluşum (Forming), Fırtına/Karmaşa (Storming), Uyumlanma (Norming) ve Performans (Performing). Bazı versiyonlara Dağılma (Adjourning) aşaması da eklenir.",
    "Variance at Completion (VAC)": "Projenin başlangıcında belirlenen Tamamlanma Bütçesi (BAC) ile güncel Tamamlama Tahmini (EAC) arasındaki fark olarak ifade edilen beklenen bütçe açığı veya fazlasının net miktarıdır.",
    "WBS Dictionary": "İş kırılım yapısındaki her bir iş paketi (bileşen) hakkında ayrıntılı teslimat, faaliyet, zaman çizelgesi ve kabul kriteri bilgileri sağlayan destekleyici belgedir.",
    "Work Breakdown Structure (WBS)": "Proje hedeflerini gerçekleştirmek için proje takımı tarafından yürütülecek toplam kapsamın, daha küçük ve yönetilebilir parçalara hiyerarşik olarak ayrıştırılmasıdır.",
}

PMBOK_RENAMES = {
    "PMBOK® Guide Principle: Adaptability & Resilience": "Embrace Adaptability & Resilience",
    "PMBOK® Guide Principle: Change": "Enable Change",
    "PMBOK® Guide Principle: Complexity": "Navigate Complexity",
    "PMBOK® Guide Principle: Leadership": "Demonstrate Leadership",
    "PMBOK® Guide Principle: Quality": "Build Quality Into Processes",
    "PMBOK® Guide Principle: Risk": "Optimize Risk Responses",
    "PMBOK® Guide Principle: Stakeholders": "Engage with Stakeholders",
    "PMBOK® Guide Principle: Stewardship": "Be a Diligent Steward",
    "PMBOK® Guide Principle: Systems Thinking": "Think Systemically",
    "PMBOK® Guide Principle: Tailoring": "Tailor Your Approach",
    "PMBOK® Guide Principle: Team": "Create a Collaborative Team Environment",
    "PMBOK® Guide Principle: Value": "Focus on Value",
}

# Apply renames + TR fields to existing terms
for t in data['terms']:
    old = t['term']
    if old in PMBOK_RENAMES:
        new_name = PMBOK_RENAMES[old]
        t['term'] = new_name
        if old in TR_NAMES:
            TR_NAMES[new_name] = TR_NAMES.get(old, TR_NAMES.get(old))
        if old in TR_DEFS:
            TR_DEFS[new_name] = TR_DEFS[old]
    name = t['term']
    if name in TR_NAMES and 'termTR' not in t:
        t['termTR'] = TR_NAMES[name]
    if name in TR_DEFS and 'definitionTR' not in t:
        t['definitionTR'] = TR_DEFS[name]

NEW_TERMS = [
    {"term":"Bottom-up Estimating","termTR":"Aşağıdan Yukarıya Tahmin","category":"Planning","definition":"A method for estimating project duration or cost by aggregating estimates of lower-level WBS components. Each work package is estimated individually and rolled up to determine the total.","definitionTR":"İş kırılım yapısının (İKY) alt düzey bileşenlerinin tahminlerini toplayarak projenin toplam süresini veya maliyetini tahmin eden bir yöntemdir.","related":["Work Breakdown Structure (WBS)","Three-Point Estimate (PERT)","Analogous Estimating","Parametric Estimating"]},
    {"term":"Fallback Plan","termTR":"B Planı / Geri Çekilme Planı","category":"Risk Management","definition":"An alternative course of action available if the primary plan must be abandoned due to issues, risks, or other circumstances. Triggered when the original risk response proves inadequate.","definitionTR":"Sorunlar, riskler veya başka nedenlerle birincil planın terk edilmesi gerektiğinde kullanılabilecek alternatif eylem ve görevler dizisidir.","related":["Risk Response Strategies","Contingency Reserve","Issue","Risk Register"]},
    {"term":"External Dependency","termTR":"Dış Bağımlılık","category":"Schedule Management","definition":"A relationship between project activities and activities outside the project that are not under the control of the organization or project team.","definitionTR":"Proje faaliyetleri ile proje dışı (organizasyonun veya projenin kontrolü dışındaki) faaliyetler arasındaki ilişkidir.","related":["Network Diagram","Lag","Critical Path","Precedence Diagramming Method (PDM)"]},
    {"term":"Ambiguity","termTR":"Belirsizlik / Muğlaklık","category":"Core Concepts","definition":"A state of uncertainty about the cause of events or conditions, or having multiple options to choose from, resulting in lack of clarity. Differs from risk (known unknowns) and complexity (many interacting elements).","definitionTR":"Nelerin veya olayların nedenini belirlemede zorluk yaşama ya da aralarından seçim yapılabilecek birden fazla seçeneğe sahip olma (belirgin olmama) durumudur.","related":["Risk","Navigate Complexity","Uncertainty Performance Domain"]},
    {"term":"Agile Center of Excellence (ACoE)","termTR":"Çevik Mükemmeliyet Merkezi / Değer Teslim Ofisi","category":"Agile & Adaptive","definition":"Organizational units (also called Value Delivery Office / VDO) that provide coaching, mentoring, and support directly to teams rather than directing them, enabling organizations to respond rapidly to changing customer needs.","definitionTR":"Ekiplerin değişen müşteri ihtiyaçlarına hızlı bir şekilde yanıt vermesi gereken kurumlarda, yöneticilik yapmak yerine doğrudan takımlara koçluk ve mentorluk sağlayan oluşumlardır.","related":["PMO (Project Management Office)","Servant Leadership","Scrum Master"]},
    {"term":"Behavior-Driven Development (BDD)","termTR":"Davranış Odaklı Geliştirme","category":"Agile & Adaptive","definition":"An extension of Test-Driven Development (TDD) where automated tests and simulations are created before the product is built, enabling quality defects to be discovered early.","definitionTR":"Ürünü geliştirmeden önce otomatik testler ve simülasyonların oluşturulduğu, Test Odaklı Geliştirme'nin (TDD) bir uzantısı olan ve kalite kusurlarını işin başında keşfetmeyi sağlayan tekniktir.","related":["Extreme Programming (XP)","Definition of Done (DoD)","User Story"]},
    {"term":"Delphi Technique","termTR":"Delphi Tekniği","category":"Planning","definition":"A method of reaching consensus in which relevant experts participate anonymously by completing surveys and sharing opinions. Responses are aggregated and fed back for further refinement until consensus is achieved.","definitionTR":"İlgili uzmanların yüz yüze gelmeden, anonim (gizli) olarak anket doldurması ve görüş bildirmesi yoluyla bir konuda fikir birliğine varılmasını sağlayan bilgi toplama yöntemidir.","related":["Brainstorming","Risk Register","Analogous Estimating"]},
    {"term":"DevOps","termTR":"DevOps","category":"Agile & Adaptive","definition":"An approach that combines Development (Dev) and Operations (Ops) through early and continuous collaboration, aiming for continuous delivery through automation. Breaks down silos between development and IT operations.","definitionTR":"Geliştirme (Development) ve operasyon (Operations) ekiplerinin erken ve sürekli işbirliğini sağlayarak, her iki alanın otomasyonu ile kesintisiz teslimatı hedefleyen yaklaşımdır.","related":["Continuous Improvement","Extreme Programming (XP)","Agile"]},
    {"term":"Artifact","termTR":"Eser / Proje Çıktısı","category":"Core Concepts","definition":"A document or other object produced during a portfolio, program, or project to assist with management and provide information to the team and stakeholders. Includes plans, reports, backlogs, and registers.","definitionTR":"Portföy, program veya proje sırasında, yönetime yardımcı olmak ve takım ile paydaşlara bilgi sağlamak amacıyla oluşturulan belge veya diğer nesnelerdir.","related":["Deliverable","Project Management Plan","Risk Register"]},
    {"term":"Vanity Metric","termTR":"Gösteriş Metriği","category":"Agile & Adaptive","definition":"A measure that appears to show achievement on the surface but provides no useful information for decision-making or improvement. Example: total page views without context, raw user counts without engagement data.","definitionTR":"Görünürde bir miktar sonuç veya başarı gösteren ancak aslında karar vermek veya iyileştirme yapmak için hiçbir faydalı bilgi sağlamayan ölçütlerdir.","related":["Velocity","Burndown Chart","Measurement Performance Domain"]},
    {"term":"Story Mapping","termTR":"Hikaye Haritalama","category":"Agile & Adaptive","definition":"A technique where groups organize user stories and visualize product functionality across a timeline. Especially useful during discovery work for prioritizing the backlog and identifying the minimum viable product.","definitionTR":"Özellikle keşif aşamasındaki çalışmalarda, daha büyük grupların kullanıcı hikayelerini organize edip ürünün işlevselliğini görselleştirmesi için kullanılan etkili bir tekniktir.","related":["User Story","Product Backlog","Minimum Viable Product (MVP)","Epic"]},
    {"term":"Bid Documents","termTR":"İhale Belgeleri","category":"Procurement","definition":"All standard documents used to request information, quotations, or proposals from potential vendors. Includes Request for Proposal (RFP), Request for Quotation (RFQ), and Invitation for Bid (IFB).","definitionTR":"Potansiyel satıcılardan bilgi, teklif (quotation) veya öneri (proposal) istemek (solicit) amacıyla kullanılan standart dokümanların tümüdür.","related":["Request for Proposal (RFP)","Bidder Conference","Contract","Procurement"]},
    {"term":"Statistical Sampling","termTR":"İstatistiksel Örnekleme","category":"Quality Management","definition":"The process of selecting only a random portion of a population to measure metrics and verify quality during quality inspection. More efficient than inspecting every item when population is large.","definitionTR":"Kalite denetimi sırasında, metrikleri ölçmek ve kaliteyi doğrulamak için ilgilenilen popülasyonun sadece rastgele bir bölümünün seçilmesi işlemidir.","related":["Control Charts","Pareto Chart","Cost of Quality (COQ)","Appraisal Cost"]},
    {"term":"Voice of the Customer","termTR":"Müşterinin Sesi","category":"Stakeholder & Communication","definition":"A technique used to translate customer requirements into appropriate technical requirements for each project phase, ensuring products truly reflect customer expectations. Captures both stated and unstated needs.","definitionTR":"Müşteri gereksinimlerini projenin her fazı için uygun teknik gereksinimlere tercüme ederek müşteri beklentilerini gerçekten yansıtan ürünler sağlamak için kullanılan tekniktir.","related":["Requirements","Stakeholder","User Story","Design Thinking"]},
    {"term":"Tacit Knowledge","termTR":"Örtük Bilgi","category":"Team & Leadership","definition":"Knowledge that is difficult to articulate, archive, and share with others, such as beliefs, personal experience, and practical insights. The opposite of explicit knowledge. Critical for knowledge transfer during project closure.","definitionTR":"İnançlar, kişisel deneyimler ve pratik içgörüler gibi kelimelere dökülmesi, arşivlenmesi ve başkalarıyla paylaşılması zor olan bilgi türüdür.","related":["Explicit Knowledge","Lessons Learned Register","Community of Practice"]},
    {"term":"Fixed-Price Incentive Fee Contract (FPIF)","termTR":"Sabit Fiyatlı Teşvik Ücretli Sözleşme","category":"Procurement","definition":"A contract type where the buyer pays the seller a defined amount, with the possibility for the seller to earn an additional incentive fee if performance criteria are exceeded or the targeted cost is underrun.","definitionTR":"Alıcının satıcıya tanımlanmış belirli bir tutarı ödediği ve satıcının performans kriterlerini aşması veya hedeflenen maliyetin altına inmesi durumunda ek bir teşvik (prim) kazandığı sözleşme türüdür.","related":["Fixed-Price Contract","Contract","Procurement"]},
    {"term":"Scrum of Scrums","termTR":"Scrum'ların Scrum'ı","category":"Agile & Adaptive","definition":"A scaled agile coordination meeting where representatives from multiple Scrum teams meet to align on dependencies, progress, and blockers across teams working simultaneously on related features.","definitionTR":"Birbiriyle ilişkili özellikler üzerinde aynı anda çalışan çoklu (ölçeklendirilmiş) çevik takımlar arasındaki bağımlılıkları ve engelleri hizalamak/koordine etmek için yapılan toplantıdır.","related":["Scrum","Daily Scrum","Scrum Master","Agile Center of Excellence (ACoE)"]},
    {"term":"Contract","termTR":"Sözleşme","category":"Procurement","definition":"A mutually binding legal agreement that obligates the seller to provide specified products, services, or results and obligates the buyer to provide monetary or other valuable consideration. Subject to remedy in courts.","definitionTR":"Tedarikçinin belirtilen ürünleri veya hizmetleri sağlamasını zorunlu kılan, alıcıyı tazmin etmeye yükümlü kılan ve mahkemelerde çözüme tabi olan bağlayıcı hukuki ilişkidir.","related":["Fixed-Price Contract","Cost Reimbursable Contract","Time and Material Contract","Procurement"]},
    {"term":"Bidder Conference","termTR":"Tedarikçi / Teklif Verenler Konferansı","category":"Procurement","definition":"A meeting held before bid submission to ensure all prospective sellers have a clear, common, and fair understanding of the procurement requirements, so no seller has privileged information.","definitionTR":"Teklif sunumundan önce, tüm olası satıcıların proje ihalesi hakkında net, ortak ve adil bir anlayışa sahip olmasını sağlamak için yapılan ön toplantıdır.","related":["Bid Documents","Request for Proposal (RFP)","Contract","Procurement"]},
    {"term":"Community of Practice","termTR":"Uygulama Topluluğu","category":"Team & Leadership","definition":"An interaction group established together with mentoring to ensure knowledge is regularly stored and transferred within the team against risks of team member departure or competency loss.","definitionTR":"İşten ayrılma riskleri veya yetkinlik kayıplarına karşı bilginin takım içinde düzenli olarak depolanmasını ve transfer edilmesini sağlamak için mentorluk ile birlikte kurulan etkileşim grubudur.","related":["Tacit Knowledge","Explicit Knowledge","Lessons Learned Register","Organizational Process Assets (OPA)"]},
    {"term":"What-If Scenario Analysis","termTR":"Ya Olursa Senaryo Analizi","category":"Risk Management","definition":"The process of evaluating alternative plans to estimate the potential impact of specific scenarios and crises on project objectives. Used to assess project viability under adverse conditions.","definitionTR":"Belirli senaryoların ve krizlerin proje hedefleri üzerindeki potansiyel etkilerini tahmin etmek amacıyla alternatif planları değerlendirme sürecidir.","related":["Monte Carlo Simulation","Risk Register","Fallback Plan","Expected Monetary Value (EMV)"]},
    {"term":"Value Stream Mapping","termTR":"Değer Akışı Haritalama","category":"Agile & Adaptive","definition":"A lean technique that visualizes all steps in a process from customer request to product delivery to identify bottlenecks, waste (muda), and process gaps. Commonly used in Lean and Kanban environments.","definitionTR":"Bir müşteri talebinden ürünün teslimine kadar geçen süreçteki tüm adımları görselleştiren, darboğazları ve israfı (waste) belirlemek için kullanılan yalın (lean) üretim tekniğidir.","related":["Lean","Kanban","Kaizen","Continuous Improvement"]},
    {"term":"Extreme Programming (XP)","termTR":"Ekstrem Programlama","category":"Agile & Adaptive","definition":"An agile software development framework focused on engineering practices such as pair programming, test-first programming (TDD), continuous integration, small releases, and refactoring.","definitionTR":"Eşli programlama (pair programming), önce-test programlama (test-first), sürekli entegrasyon ve süreçlerin metafor olarak adlandırılması gibi mühendislik pratiklerine odaklanan çevik bir yazılım geliştirme çerçevesidir.","related":["Pair Programming","Behavior-Driven Development (BDD)","Agile","DevOps"]},
    {"term":"Pair Programming","termTR":"Eşli Programlama","category":"Agile & Adaptive","definition":"An Extreme Programming (XP) practice where two team members work together at a single workstation. One writes code (driver) while the other reviews in real time (navigator). Roles are switched regularly.","definitionTR":"İki takım üyesinin tek bir iş istasyonunda birlikte çalıştığı, biri işi yaparken diğerinin anında gözden geçirip hata aradığı bir Ekstrem Programlama (XP) pratiğidir.","related":["Extreme Programming (XP)","Technical Debt","Definition of Done (DoD)"]},
    {"term":"Service Level Agreement (SLA)","termTR":"Hizmet Seviyesi Anlaşması","category":"Procurement","definition":"A formal contract between a service provider and a buyer that defines agreed-upon performance measurements, response times, uptime guarantees, and quality standards. Commonly used in IT and outsourcing contracts.","definitionTR":"Alıcı ve hizmet sağlayıcı arasında yapılan, her iki tarafça kabul edilen performans ölçümlerine, teslimat sürelerine ve hizmet kalitesine odaklanan özel bir sözleşme türüdür.","related":["Contract","Fixed-Price Contract","Procurement"]},
    {"term":"Proof of Concept (POC)","termTR":"Kavram Kanıtlama","category":"Agile & Adaptive","definition":"A small-scale prototype or experiment developed to demonstrate that an idea, design, or solution is technically and economically feasible before committing full resources. Reduces uncertainty early in the project.","definitionTR":"Bir fikrin, tasarımın veya çözümün teknik ve ekonomik olarak uygulanabilir olup olmadığını organizasyona göstermek için geliştirilen küçük ölçekli ve hızlı kanıt veya test modelidir.","related":["Minimum Viable Product (MVP)","Spike","Iterative Approach","Risk Response Strategies"]},
    {"term":"Crystal Methods","termTR":"Kristal Metodolojiler","category":"Agile & Adaptive","definition":"A family of agile methodologies developed by Alistair Cockburn where processes are tailored to the team size, project criticality, and priorities. Places people and interactions over rigid processes.","definitionTR":"Takımın büyüklüğüne, projenin kritikliğine ve önceliklerine göre süreçlerin takıma özel olarak uyarlandığı, insan etkileşimini süreçlerin önüne koyan esnek çevik metodolojiler grubudur.","related":["Agile","Hybrid Approach","Tailoring","Scrum"]},
    {"term":"Organizational Cultural Intelligence","termTR":"Kurumsal Kültürel Zeka","category":"Team & Leadership","definition":"The ability of an organization, project manager, and teams to recognize and leverage cultural differences to work effectively and harmoniously in culturally diverse, complex, and multinational environments.","definitionTR":"Kurumun, proje yöneticisinin ve takımların, kültürel olarak çeşitli, karmaşık ve çok uluslu ortamlarda farklılıkları tanıyıp bunlardan faydalanarak etkili bir şekilde ve uyum içinde çalışma yeteneğidir.","related":["Emotional Intelligence (EI)","Active Listening","Stakeholder"]},
    {"term":"Minimum Marketable Feature (MMF)","termTR":"Minimum Pazarlanabilir Özellik","category":"Agile & Adaptive","definition":"The smallest functional feature set that adds immediate value to the customer and can be released for general use. Unlike MVP (a learning vehicle), MMF is a fully finished, marketable addition to the product.","definitionTR":"Müşteriye hemen değer katacak ve genel kullanıma hazır olarak pazara sürülebilecek en küçük işlevsel özellik setidir. MVP'nin aksine, MMF tamamen bitmiş ve pazarlanabilir bir ektir.","related":["Minimum Viable Product (MVP)","User Story","Product Backlog","Feature"]},
    {"term":"Feature-Driven Development (FDD)","termTR":"Özellik Odaklı Geliştirme","category":"Agile & Adaptive","definition":"An agile framework focused on modeling and delivering the project according to small customer-valued features. Designed for large-scale software development projects. Emphasizes domain-object modeling and feature lists.","definitionTR":"Müşteri için küçük iş değeri taşıyan yeteneklere (özelliklere) göre projeyi modellemeye ve planlamaya odaklanan, özellikle büyük ölçekli yazılım geliştirme projelerinin ihtiyaçları için tasarlanmış bir çerçevedir.","related":["Agile","User Story","Feature","Scrum"]},
    {"term":"Roman Voting","termTR":"Roma Oylaması","category":"Agile & Adaptive","definition":"A rapid consensus-building technique where team members simultaneously show thumbs up (approve), thumbs down (reject), or sideways (neutral/abstain) to indicate agreement or disagreement.","definitionTR":"Takımın bir fikre veya karara katılıp katılmadığını eşzamanlı olarak başparmaklarını yukarı (onay), aşağı (ret) veya yana (kararsız/çekimser) çevirerek gösterdikleri hızlı fikir birliği tekniğidir.","related":["Voting Techniques","Planning Poker","Retrospective"]},
    {"term":"Fishbowl","termTR":"Akvaryum (Sanal Ofis)","category":"Team & Leadership","definition":"A permanently open video conference window maintained throughout working hours to give geographically distributed (virtual) teams a constant presence, making them feel like they are in the same office.","definitionTR":"Coğrafi olarak dağıtılmış (sanal) takımlarda kalıcı bir görüş alanı sağlamak, 'aynı ofisteymiş gibi' hissettirmek ve gerçek zamanlı etkileşimi artırmak için çalışma saatleri boyunca sürekli açık bırakılan video konferans penceresidir.","related":["Information Radiator","Daily Scrum","Communication Methods"]},
    {"term":"Initiating Process Group","termTR":"Başlatma Süreç Grubu","category":"Core Concepts","definition":"The group of activities that begins a new project or a new phase of an existing project, defining the project boundaries and resulting in formal authorization. Key outputs include the Project Charter and stakeholder identification.","definitionTR":"Yeni bir projenin veya mevcut bir projenin yeni bir fazının yetkilendirilmesiyle sonuçlanabilecek süreci başlatan ve proje sınırlarını çizen faaliyetler grubudur.","related":["Project Charter","Sponsor","Stakeholder Register","Project Management Plan"]},
    {"term":"Brainstorming","termTR":"Beyin Fırtınası","category":"Planning","definition":"A creative group technique used to generate ideas, gather data, identify risks, or elicit requirements. Participants freely contribute ideas without criticism. Quantity of ideas is encouraged in the initial phase.","definitionTR":"Veri toplamak, yeni fikirler üretmek veya riskleri ve gereksinimleri belirlemek için takım veya uzmanlarla birlikte kullanılan çok yönlü bir yaratıcılık tekniğidir.","related":["Delphi Technique","Risk Register","Requirements","Brainwriting"]},
    {"term":"Gantt Chart","termTR":"Gantt Şeması","category":"Schedule Management","definition":"A horizontal bar chart that visualizes the project schedule by showing the start dates, end dates, and durations of project activities. Named after Henry Gantt. One of the most widely used project management tools.","definitionTR":"Proje faaliyetlerinin zaman çizelgesini görselleştiren, görevlerin başlangıç, bitiş tarihleri ve sürelerini yatay çubuklar yardımıyla sunan yaygın bir grafiksel araçtır.","related":["Critical Path","Milestone","Schedule Baseline","Float (Slack)"]},
    {"term":"Requirements Traceability Matrix","termTR":"Gereksinim İzlenebilirlik Matrisi","category":"Scope Management","definition":"A formal document that links requirements to their origin and tracks them throughout the project life cycle to ensure all objectives are met and no requirements are lost or changed without control.","definitionTR":"Gereksinimleri kökenlerine bağlayan ve hedeflerin karşılandığından emin olmak için proje yaşam döngüsü boyunca onları adım adım izleyen resmi belgedir.","related":["Requirements","Scope Baseline","Work Breakdown Structure (WBS)","Acceptance Criteria"]},
    {"term":"Scope","termTR":"Kapsam","category":"Scope Management","definition":"The sum of the products, services, and results to be provided as a project. Defines all the work — and only the work — required to complete the project successfully.","definitionTR":"Bir proje kapsamında ortaya konulması veya sağlanması gereken ürünlerin, hizmetlerin ve sonuçların toplamıdır.","related":["Scope Baseline","Scope Creep","Work Breakdown Structure (WBS)","Requirements"]},
    {"term":"Spike","termTR":"Sıçrama (Spike)","category":"Agile & Adaptive","definition":"A time-boxed research or exploration task carried out by an agile team to investigate a technology, reduce uncertainty, or understand a problem. Results inform future work but may not produce shippable software.","definitionTR":"Özellikle çevik projelerde, bir teknolojiyi denemek, pazar belirsizliğini azaltmak veya bir sorunu anlamak amacıyla takımın belli bir zaman kutusunda yürüttüğü hedefli analiz ve araştırma görevidir.","related":["Proof of Concept (POC)","Timeboxing","Sprint","User Story"]},
    {"term":"T-Shaped Team Member","termTR":"T-Şekilli Takım Üyesi","category":"Team & Leadership","definition":"A team profile with broad general knowledge across multiple disciplines (horizontal bar of the T) and deep expertise in one specific area (vertical bar of the T). Enables flexibility and cross-functional collaboration.","definitionTR":"Çevik projelerde tercih edilen, yatay düzlemde birden çok disiplin hakkında genel bilgiye sahipken, dikey düzlemde belirli bir uzmanlık alanında çok derin beceriye sahip olan yetenekli takım profilidir.","related":["Scrum","Velocity","Servant Leadership"]},
    {"term":"Procurement","termTR":"Tedarik","category":"Procurement","definition":"The processes of acquiring goods, services, subcontracting, or external resources needed for project success from outside the organization through formal contracts. Includes planning, conducting, and controlling procurement.","definitionTR":"Projenin başarılı olması için ihtiyaç duyulan mal, hizmet, taşeronluk veya dış kaynakların kurum dışından resmi sözleşmeler yoluyla satın alınması süreçleridir.","related":["Contract","Fixed-Price Contract","Request for Proposal (RFP)","Bid Documents"]},
    {"term":"Benefit","termTR":"Fayda","category":"Core Concepts","definition":"A gain or value realized or perceived by the organization or stakeholders as a result of delivered project outputs. Represents the positive change achieved, not just the output produced.","definitionTR":"Teslim edilen proje çıktılarının bir sonucu olarak organizasyon veya paydaşlar tarafından elde edilen veya algılanan kazanç ya da değerdir.","related":["Benefits Realization","Business Value","Business Case","Outcome"]},
    {"term":"Explicit Knowledge","termTR":"Açık Bilgi","category":"Team & Leadership","definition":"Knowledge that can be easily codified, documented, and directly transferred to others using numbers, words, images, and symbols. The opposite of Tacit Knowledge. Examples include manuals, procedures, and databases.","definitionTR":"Rakamlar, kelimeler, resimler ve semboller kullanılarak kolayca kodlanabilen, dokümante edilip başkalarına doğrudan aktarılabilen (Örtük Bilginin zıttı) bilgi türüdür.","related":["Tacit Knowledge","Lessons Learned Register","Organizational Process Assets (OPA)"]},
    {"term":"Active Listening","termTR":"Aktif Dinleme","category":"Stakeholder & Communication","definition":"A conscious communication skill used to correctly understand the speaker's message, reduce miscommunications (especially in virtual and multicultural teams), and identify and remove communication barriers.","definitionTR":"Karşıdaki kişinin mesajını doğru anlamak, yanlış iletişimleri (özellikle sanal ve çok kültürlü takımlarda) azaltmak ve iletişimin önündeki engelleri fark edip ortadan kaldırmak için kullanılan bilinçli dinleme becerisidir.","related":["Communication Methods","Emotional Intelligence (EI)","Stakeholder"]},
    {"term":"Analogous Estimating","termTR":"Benzerlik Tahmini","category":"Planning","definition":"A technique that uses historical data from similar past projects to estimate the current project's cost or duration. A 'top-down' approach — less accurate than bottom-up but faster and requires less detail.","definitionTR":"Geçmişteki benzer projelerin veya faaliyetlerin süre ve maliyet verilerini kullanarak, mevcut projenin maliyet veya süresini 'yukarıdan aşağıya' tahmin etme yöntemidir.","related":["Bottom-up Estimating","Parametric Estimating","Three-Point Estimate (PERT)"]},
    {"term":"Critical Thinking","termTR":"Eleştirel Düşünme","category":"Team & Leadership","definition":"The ability to analyze information objectively, reflectively, and logically to recognize biases, identify root causes of problems, and overcome challenges such as ambiguity and complexity.","definitionTR":"Önyargıları tanımak, sorunların kök nedenlerini belirlemek, belirsizlik ve karmaşıklık gibi zorlukların üstesinden gelmek için bilgiyi objektif, yansıtıcı ve mantıksal bir şekilde analiz etme yeteneğidir.","related":["Ambiguity","Confirmation Bias","Cause-and-Effect Diagram","Decision Tree Analysis"]},
    {"term":"Impediment","termTR":"Engel / Bloker","category":"Agile & Adaptive","definition":"Any external or internal factor that prevents the team from reaching their goals or completing their work. In Scrum, removing impediments is the Scrum Master's primary responsibility. Also called a blocker.","definitionTR":"Takımın hedeflerine ulaşmasını engelleyen herhangi bir dış veya iç faktördür. Çevik projelerde bunları ortadan kaldırmak Scrum Master'ın birincil görevidir.","related":["Scrum Master","Daily Scrum","Risk","Issue"]},
    {"term":"Escalation","termTR":"Eskalasyon / Yükseltme","category":"Stakeholder & Communication","definition":"The formal process of transferring an issue, risk, or decision to a higher level of management when resolution exceeds the project manager's authority, resources, or capability.","definitionTR":"Bir sorunun veya riskin çözümünün, proje yöneticisinin yetkisini veya kontrolünü aşması durumunda üst yönetime (sponsor, PMO vb.) resmi olarak devredilmesidir.","related":["Issue Log","Risk Register","Sponsor","PMO (Project Management Office)"]},
    {"term":"Confirmation Bias","termTR":"Onay Önyargısı","category":"Core Concepts","definition":"A cognitive bias in project decision-making where people favor information that confirms their pre-existing beliefs while ignoring contradictory data. Can lead to poor risk assessment and project failures.","definitionTR":"Proje karar alma süreçlerinde, insanların sadece kendi önceden var olan inançlarını doğrulayan bilgileri dikkate alıp, tersini gösteren verileri yok sayması şeklindeki bilişsel hatadır.","related":["Critical Thinking","Risk","Decision Tree Analysis","Ambiguity"]},
    {"term":"Voting Techniques","termTR":"Oylama Teknikleri","category":"Agile & Adaptive","definition":"Methods used by teams to reach decisions: Unanimity (everyone agrees), Majority (>50% support), Plurality (largest block wins even without majority), and Dictatorship (one person decides).","definitionTR":"Takımın kararlara ulaşmak için kullandığı yöntemler: Oybirliği (herkesin aynı fikirde olması), Çoğunluk (%50'den fazla destek), Göreceli Çoğunluk (en büyük bloğun kararı) ve Diktatörlük (tek kişi karar verir).","related":["Roman Voting","Planning Poker","Retrospective"]},
    {"term":"Parametric Estimating","termTR":"Parametrik Tahmin","category":"Planning","definition":"A technique that uses statistical relationships between historical data and project variables (e.g., cost per square meter, hours per function point) to calculate project cost or duration with high accuracy.","definitionTR":"Geçmiş veriler ile proje değişkenleri arasındaki istatistiksel ilişkiyi kullanarak projenin maliyetini veya süresini yüksek doğrulukla hesaplama yöntemidir.","related":["Analogous Estimating","Bottom-up Estimating","Three-Point Estimate (PERT)"]},
    {"term":"Transparency","termTR":"Şeffaflık","category":"Team & Leadership","definition":"A core agile value and servant leadership principle where people openly and honestly share their work in progress, successes, failures, and current status without fear. Enables informed decisions and builds trust.","definitionTR":"Özellikle çevik yaklaşımlarda ve hizmetkar liderlikte, insanların ara teslimatlarını, başarılarını, başarısızlıklarını ve mevcut durumu korkusuzca, dürüst ve açık bir şekilde paylaşma kültürüdür.","related":["Information Radiator","Servant Leadership","Agile","Retrospective"]},
    {"term":"Design Thinking","termTR":"Tasarım Odaklı Düşünme","category":"Agile & Adaptive","definition":"A human-centered problem-solving approach that aims to create user-centered innovations by building deep empathy with customers, rapid prototyping, and iterating based on feedback.","definitionTR":"Karmaşık problemleri çözerken veya ürün gereksinimlerini toplarken müşteriyle derin bir empati kurmayı, prototiplemeyi ve iteratif olarak kullanıcı merkezli yenilikler üretmeyi hedefleyen yaklaşımdır.","related":["Voice of the Customer","User Story","Proof of Concept (POC)","Minimum Viable Product (MVP)"]},
    {"term":"Generative AI","termTR":"Üretken Yapay Zeka","category":"Core Concepts","definition":"Next-generation AI systems introduced to project management literature with PMBOK 8, capable of generating text, code, images, or project data, providing predictions, and supporting decision-making processes.","definitionTR":"PMBOK 8 ile literatüre giren, metin, kod, görüntü veya proje verisi üretmek, öngörüler sağlamak ve karar alma süreçlerini desteklemek için kullanılan yeni nesil yapay zeka sistemleridir.","related":["Agile","Continuous Improvement","Project Management"]},
    {"term":"Validation","termTR":"Validasyon / Geçerlilik Kılma","category":"Quality Management","definition":"The process of confirming that a deliverable meets the customer's actual needs and expected business value. Answers: 'Did we build the right product?' Distinct from Verification which checks technical compliance.","definitionTR":"Teslim edilen ürünün veya hizmetin, müşterinin gerçek ihtiyaçlarını ve beklenen iş değerini karşılayıp karşılamadığının kanıtlanmasıdır. (Doğru ürünü mü yaptık?)","related":["Verification","Acceptance Criteria","Definition of Done (DoD)"]},
    {"term":"Verification","termTR":"Doğrulama (Verifikasyon)","category":"Quality Management","definition":"The process of checking through quality control that the product has been produced in accordance with defined technical requirements, specifications, or regulations. Answers: 'Did we build the product right?'","definitionTR":"Ürünün, belirlenen teknik gereksinimlere, spesifikasyonlara veya regülasyonlara uygun olarak üretilip üretilmediğinin kalite kontrol süreçleriyle kontrol edilmesidir. (Ürünü doğru mu yaptık?)","related":["Validation","Control Charts","Acceptance Criteria","Definition of Done (DoD)"]},
    {"term":"Successor Activity","termTR":"Ardıl Faaliyet","category":"Schedule Management","definition":"An activity that logically comes after another activity (the predecessor) in a project schedule and depends on it. The nature of the dependency is defined by the relationship type (FS, FF, SS, SF).","definitionTR":"Bir zaman çizelgesinde mantıksal olarak başka bir faaliyetten (öncül faaliyetten) sonra gelen ve ona bağımlı olan faaliyettir.","related":["Precedence Diagramming Method (PDM)","Network Diagram","Critical Path","Lag"]},
    {"term":"Brainwriting","termTR":"Beyin Yazımı","category":"Planning","definition":"A creative technique where team members silently write their ideas on paper or digitally instead of voicing them, after which ideas are passed around the group for further development. Overcomes groupthink.","definitionTR":"Geleneksel beyin fırtınasının aksine, takım üyelerinin fikirlerini sesli söylemek yerine sessizce yazıp daha sonra grupta dolaştırarak geliştirdikleri yaratıcılık tekniğidir.","related":["Brainstorming","Delphi Technique","Risk Register"]},
    {"term":"Cognitive Bias","termTR":"Bilişsel Önyargı","category":"Core Concepts","definition":"A systematic pattern of deviation from rational judgment in project decision-making. Examples include confirmation bias and anchoring bias. Self-awareness and structured decision processes help mitigate its effects.","definitionTR":"Proje yöneticisinin veya takımın karar almasını olumsuz etkileyen; verileri kendi inançlarına uydurma veya yanıltıcı varsayımlarda bulunma gibi zihinsel hata durumlarıdır.","related":["Confirmation Bias","Critical Thinking","Risk","Decision Tree Analysis"]},
    {"term":"Design of Experiments (DOE)","termTR":"Deney Tasarımı","category":"Quality Management","definition":"A statistical method used in quality management to determine which variables (factors) have the greatest influence on specific product or process characteristics. Helps optimize quality by systematically varying multiple factors.","definitionTR":"Kalite yönetiminde, bir ürünün veya sürecin geliştirilmesi sırasında hangi faktörlerin belirli özellikler üzerinde en büyük etkiye sahip olduğunu belirlemek için kullanılan istatistiksel yöntemdir.","related":["Statistical Sampling","Control Charts","Six Sigma","Cause-and-Effect Diagram"]},
    {"term":"Status Meetings","termTR":"Durum Toplantıları","category":"Stakeholder & Communication","definition":"Regularly scheduled communication events to update stakeholders and team members on the project's current status, progress, and performance metrics. Key tool for maintaining stakeholder engagement and transparency.","definitionTR":"Projenin mevcut durumunu, ilerlemesini ve performans metriklerini paydaşlara ve takım üyelerine aktarmak için düzenlenen düzenli iletişim etkinlikleridir.","related":["Communications Management Plan","Information Radiator","Stakeholder Engagement Plan"]},
    {"term":"Activity Attributes","termTR":"Faaliyet Nitelikleri","category":"Schedule Management","definition":"Multiple data elements associated with each scheduled activity, including activity codes, predecessor/successor activities, logical relationships, leads and lags, resource requirements, constraints, and assumptions.","definitionTR":"Zaman çizelgesindeki her bir faaliyetin özelliklerini tanımlayan; faaliyetin kodunu, açıklamasını, öncül/ardıl ilişkilerini, kaynak gereksinimlerini ve kısıtlarını içeren çoklu veri setleridir.","related":["Network Diagram","Critical Path Method (CPM)","Work Breakdown Structure (WBS)"]},
    {"term":"Benefits Owner","termTR":"Fayda Sahibi","category":"Core Concepts","definition":"The individual responsible for monitoring, measuring, and verifying whether the benefits produced by a project or program have been realized in operational life. Accountable for benefits realization after project closure.","definitionTR":"Projenin veya programın ürettiği faydaları izlemekten, ölçmekten ve bu faydaların operasyonel hayata geçip geçmediğini doğrulamaktan sorumlu olan kişidir.","related":["Benefits Realization","Sponsor","Business Case","Outcome"]},
    {"term":"Claim","termTR":"Hak Talebi / İddia","category":"Procurement","definition":"In procurement contracts, a request or assertion by one party for consideration, compensation, or payment. Typically arises from disputed changes, differing conditions, or breach of contract. Handled through claims administration.","definitionTR":"Tedarik sözleşmelerinde, alıcı ile satıcı arasında şartlar, değişiklikler veya ödemeler konusunda bir anlaşmazlık olduğunda taraflardan birinin yasal/sözleşmesel olarak talep ettiği hak, itiraz veya tazminattır.","related":["Contract","Change Request","Procurement"]},
    {"term":"Checklist","termTR":"Kontrol Listesi","category":"Quality Management","definition":"A structured tool used during quality control or project closure to verify that a required set of steps has been performed or that specific quality standards have been met. Ensures consistency and completeness.","definitionTR":"Kalite kontrol veya proje kapanışı sırasında, gerekli bir dizi adımın uygulandığını veya belirli standartlara uyulduğunu doğrulamak için kullanılan yapılandırılmış bir araçtır.","related":["Definition of Done (DoD)","Acceptance Criteria"]},
    {"term":"Summary Activity","termTR":"Özet Faaliyet","category":"Schedule Management","definition":"In a project schedule, a grouping of related sub-activities shown as a single comprehensive activity or phase. Used in Gantt charts to provide a high-level view. Also called a 'hammock activity'.","definitionTR":"Zaman çizelgesinde, birbiriyle ilişkili birden çok alt faaliyetin toplanarak tek bir kapsamlı faaliyet veya aşama olarak gösterildiği yapıdır.","related":["Gantt Chart","Work Breakdown Structure (WBS)","Milestone"]},
    {"term":"Dormancy","termTR":"Pasiflik / Gecikme Süresi","category":"Risk Management","definition":"The time elapsed between when a risk event occurs and when its impact on the project is actually noticed or felt. A short dormancy period gives less time to respond before impact is realized.","definitionTR":"Risk yönetiminde, bir riskin (veya olayın) gerçekleştiği an ile bu riskin proje üzerindeki etkisinin 'fark edildiği' an arasında geçen süredir.","related":["Risk","Risk Register","Issue","Risk Appetite"]},
    {"term":"Variance","termTR":"Sapma","category":"Core Concepts","definition":"A measurable deviation, departure, or difference from a known baseline or expected value. Variances in scope, cost, or schedule trigger corrective or preventive actions.","definitionTR":"Projenin bilinen veya onaylanmış temel çizgisinden (beklenen değerinden) ölçülebilir düzeyde uzaklaşması, sapması veya ayrılmasıdır.","related":["Variance Analysis","Cost Variance (CV)","Schedule Variance (SV)","Variance at Completion (VAC)"]},
    {"term":"Variance Analysis","termTR":"Sapma Analizi","category":"Earned Value Management","definition":"A technique for comparing actual project performance to the approved baseline to determine the cause and magnitude of differences in scope, cost, or schedule. Enables informed corrective actions.","definitionTR":"Kapsam, maliyet veya zaman çizelgesindeki gerçekleşen performansın, onaylanmış temel çizgiyle karşılaştırılarak aradaki farkların nedenlerini ve etkilerini belirleme tekniğidir.","related":["Variance","Cost Variance (CV)","Schedule Variance (SV)","Earned Value Management (EVM)"]},
    {"term":"Stacey Complexity Model","termTR":"Stacey Karmaşıklık Modeli","category":"Core Concepts","definition":"A framework that determines a project's complexity level (Simple, Complicated, Complex, Chaotic) by mapping how well requirements (scope) are understood against how well the technology/method to build them is known.","definitionTR":"Bir projenin gereksinimlerinin ne kadar iyi anlaşıldığı (Kapsam) ile bunları oluşturmak için gereken teknolojinin ne kadar iyi bilindiği (Teknoloji) arasındaki ilişkiye bakarak projenin karmaşıklık düzeyini belirleyen değerlendirme aracıdır.","related":["Navigate Complexity","Tailoring","Hybrid Approach","Ambiguity"]},
    {"term":"SWOT Analysis","termTR":"SWOT Analizi","category":"Planning","definition":"A strategic analysis framework that identifies an organization's or project's Strengths, Weaknesses, Opportunities, and Threats. Used in risk identification, strategic planning, and stakeholder analysis.","definitionTR":"Bir kurumun, projenin veya seçeneğin; Güçlü Yönlerini (Strengths), Zayıf Yönlerini (Weaknesses), Fırsatlarını (Opportunities) ve Tehditlerini (Threats) analiz etmeye yarayan risk ve strateji aracıdır.","related":["Risk Register","Risk Response Strategies","Assumption","Brainstorming"]},
    {"term":"Body Language","termTR":"Vücut Dili","category":"Stakeholder & Communication","definition":"Non-verbal physical communication through facial expressions, gestures, and posture that often conveys more information than words. Critical in the message encoding/decoding phases of communication.","definitionTR":"İletişim süreçlerinde, özellikle mesajın kodlanması ve kodunun çözülmesi aşamalarında kelimelerden çok daha fazla etkiye sahip olan; yüz ifadeleri, jestler ve duruşu içeren fiziksel bilgi aktarımıdır.","related":["Active Listening","Communication Methods","Emotional Intelligence (EI)"]},
]

existing = {t['term'].lower() for t in data['terms']}
added = 0
for nt in NEW_TERMS:
    if nt['term'].lower() not in existing:
        data['terms'].append(nt)
        existing.add(nt['term'].lower())
        added += 1
    else:
        for t in data['terms']:
            if t['term'].lower() == nt['term'].lower():
                if 'termTR' not in t and 'termTR' in nt:
                    t['termTR'] = nt['termTR']
                if 'definitionTR' not in t and 'definitionTR' in nt:
                    t['definitionTR'] = nt['definitionTR']
                break

data['terms'].sort(key=lambda t: t['term'].lower())

with open(json_path, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Done! Total terms: {len(data['terms'])} | Added {added} new terms")
